---
# https://gha-trigger.github.io/github-actions/#update-commit-statuses-per-workflow
name: Test Pull Request (Update commit status per workflow)
on:
  workflow_dispatch:
    inputs:
      data:
        required: true
env:
  AQUA_CONFIG: ${{github.workspace}}/.ci/aqua.yaml
  GHA_WORKFLOW_COMMIT_STATUS: "true"
jobs:
  gha-trigger-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: gha-trigger/step-summary-action@v0.1.1
        with:
          data: ${{inputs.data}}

  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$INPUT" | jq
        env:
          INPUT: ${{inputs.data}}

      - uses: gha-trigger/start-action@v0.1.6
        id: start
        with:
          data: ${{inputs.data}}
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}
          start_workflow: true

      - run: |
          echo "$GITHUB_REPOSITORY" # CI Repository
          . "$GHA_ENV" # Overwrite default environment variables GITHUB_*
          echo "$GITHUB_REPOSITORY" # Main Repository

      - uses: gha-trigger/end-action@v0.1.2
        if: always()
        with:
          github_token: ${{steps.start.outputs.github_app_token}}
          state: ${{job.status}}

  status-check:
    runs-on: ubuntu-latest
    needs: [test-pull-request, gha-trigger-summary]
    if: always()
    steps:
      - uses: gha-trigger/start-action@v0.1.6
        id: start
        with:
          data: ${{inputs.data}}
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      - uses: gha-trigger/end-action@v0.1.2
        if: always()
        with:
          github_token: ${{steps.start.outputs.github_app_token}}
          needs: ${{toJson(needs)}}
