---
name: Test Push
on:
  workflow_dispatch:
    inputs:
      data:
        required: true
env:
  AQUA_CONFIG: ${{github.workspace}}/.ci/aqua.yaml
jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$INPUT" | jq
        env:
          INPUT: ${{inputs.data}}

      - uses: gha-trigger/start-action@main
        id: start
        with:
          data: ${{inputs.data}}
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.5'

      - run: go run .
        working-directory: foo
        env:
          GITHUB_TOKEN: ${{steps.start.outputs.github_app_token}}

      - uses: gha-trigger/end-action@main
        if: always()
        with:
          github_token: ${{steps.start.outputs.github_app_token}}
          state: ${{job.status}}
