---
name: Test Push
on:
  workflow_dispatch:
    inputs:
      data:
        required: true
env:
  AQUA_CONFIG: ${{github.workspace}}/.ci/aqua.yaml
jobs:
  gha-trigger-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: gha-trigger/step-summary-action@v0.1.1
        with:
          data: ${{inputs.data}}

  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$INPUT" | jq
        env:
          INPUT: ${{inputs.data}}

      - uses: gha-trigger/start-action@v0.1.4
        id: start
        with:
          data: ${{inputs.data}}
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}

      - run: cat README.md

      - uses: gha-trigger/end-action@v0.1.3
        if: always()
        with:
          github_token: ${{steps.start.outputs.github_app_token}}
          state: ${{job.status}}
